services:
  postgres-db:
    image: postgres:latest
    container_name: project-error_handling
    restart: no
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - project_error_handling_data:/var/lib/postgresql/data

volumes:
  project_error_handling_data: