server:
  port: 8080

spring:
  application:
    name: error-handling

# เข้มงวดเรื่อง key ห้ามเกิน
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-missing-creator-properties: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration